version: "3.3"
services:
  mysql:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=bookproject
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword

    ports:
      - 3366:3306
    volumes:
      - ./mysql-volume:/var/lib/mysql