name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install
        run: |
          npm install --force
        
      - name: Build project
        run: |
          npm run build
