name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install
        run: |
          cd ./frontend/
          npm install --force
        
      - name: Build project
        run: |
          npm run build
          
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install
        run: |
          cd ./backend/
          npm install --force
        
      - name: Build project
        run: |
          tsc --build
    
